M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Mon 20 Jun 2022 01:28:01 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-20T13:28:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1358
%
G90
G05
T1
X3.8232Y-5.43
X4.0508Y-5.43
T2
X4.252Y-2.3504
X4.252Y-2.4685
T3
X3.622Y-2.5224
T4
X3.622Y-5.0236
X4.252Y-2.8504
T0
M30
